Update rebase.yml

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -86,8 +86,8 @@ jobs:
           git clone https://gitlab.com/OrangeFox/sync.git -b master
           cd sync
           mkdir -p ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/.repo/local_manifests
-          echo '<?xml version="1.0" encoding="UTF-8"?><manifest><project name="OrangeFoxRecovery/recovery" path="bootable/recovery" remote="github" revision="fox_12.1" /><project name="TeamWin/android_vendor_twrp" path="vendor/twrp" remote="github" revision="android-12.1" /></manifest>' > ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/.repo/local_manifests/roomservice.xml
-          ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }} || { echo "Error: orangefox_sync.sh failed"; cat orangefox_sync.log || true; exit 1; }
+          echo '<?xml version="1.0" encoding="UTF-8"?><manifest><remove-project name="TeamWin/android_bootable_recovery" /><project name="OrangeFoxRecovery/recovery" path="bootable/recovery" remote="github" revision="fox_12.1" /><project name="TeamWin/android_vendor_twrp" path="vendor/twrp" remote="github" revision="android-12.1" /></manifest>' > ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/.repo/local_manifests/roomservice.xml
+          ./orangefox_sync.sh --branch twrp-${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }} > orangefox_sync.log 2>&1 || { echo "Error: orangefox_sync.sh failed"; cat orangefox_sync.log || true; exit 1; }
 
       # Clone the device tree
       - name: Clone Device Tree
